export const initialArticles = [
  {
    id: 1,
    sport : "Cricket",
    title: "Article 1",
    summary: "Summary for Article 1",
    thumbnail: "article1.jpg",
    details : "details of the summary",
    
  },
  {
    id: 2,
    sport : "Cricket",
    title: "Article 2",
    summary: "Summary for Article 2",
    thumbnail: "article2.jpg",
    details : "details of the summary",
  },
  {
    id: 3,
    sport : "Badminton",
    title: "Article 3",
    summary: "Summary for Article 3",
    thumbnail: "article3.jpg",
    details : "details of the summary",
  },
  {
    id: 4,
    sport : "Chess",
    title: "Article 4",
    summary: "Summary for Article 4",
    thumbnail: "article4.jpg",
    details : "details of the summary",
  },
  {
    id: 5,
    sport : "Football",
    title: "Article 5",
    summary: "Summary for Article 5",
    thumbnail: "article5.jpg",
    details : "details of the summary",
  },
  {
    id: 6,
    sport : "hockey",
    title: "Article 6",
    summary: "Summary for Article 6",
    thumbnail: "article6.jpg",
    details : "details of the summary",
  },
];
